#ESTE ES EL ARCHIVO PYTHON EN EL CUAL MIS COMPAÑEROS Y YO 
# TRABAJAREMOS PARA CREAR UNA CALCULADORA DE MANERA COLABORATIVA

mkihjfdx5

miau miau


por la cresta los super 8 estan a 300 y 2 por 500


